### ISSUE TITLE
mysql over ssl

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/user_sql#101]
Hi, is it possible enable user_sql connection over ssl?
Thanks.

**Comment by mlojewski-me** [comment]
By SSL you meant to set the following properties?
PDO::MYSQL_ATTR_SSL_KEY
PDO::MYSQL_ATTR_SSL_CERT
PDO::MYSQL_ATTR_SSL_CA

**Comment by johnwmail** [comment]
yes
