### ISSUE TITLE
No possibility for hash_hmac authentication

### ISSUE THREAD

**Issue by PB-SF** [nextcloud/user_sql#102]
I have a database where users' passwords are stored using ```hash_hmac```. Unfortunately, this option does not exist in the selection of the user_sql backend. Would it be possible to add this encryption?

**Comment by mlojewski-me** [comment]
Yes, it would. I will look at it soon.

**Comment by PB-SF** [comment]
Very cool... :)

**Comment by mlojewski-me** [comment]
I looked at the documentation and what I see I can do is to add new algorithm with option to type name of hashing algorithm and the key will be taken from salt column.
https://www.php.net/manual/en/function.hash-hmac.php

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/d7735280a0c0e21096d98937d5412887bff7e313
