### ISSUE TITLE
Auto join SQL users into NC group?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#107]
Would be nice if there was an option to set which allows adding all SQL users to an additional Nextcloud group.

This would be useful for basic setups without groups from the SQL backend and also for easy management of users in a mixed login setup.

Thanks!

**Comment by mlojewski-me** [comment]
I would be possible to add new option 'Default group' and if group backend would not specified assigned all SQL users to this group.

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/a483168890684de0ab8a8b920497ef2219f70b74
