### ISSUE TITLE
App is temporarily inactive

### ISSUE THREAD

**Issue by Saliman-Banana** [nextcloud/user_sql#112]
Hello, 

we have a problem. The app "User and Group SQL Backends" temporarily switches to inactive. Then we can no longer log in with the deposited users.

Best regards
Saliman

**Comment by mlojewski-me** [comment]
Can you provide any logs?
I think it switches to inactive when exception in the app occurs.

**Comment by Saliman-Banana** [comment]
Where exactly can I find the logs?

Best regards
Martin
8. Oktober 2019 20:05, "Marcin Łojewski" <notifications@github.com (mailto:notifications@github.com?to=%22Marcin%20%C5%81ojewski%22%20<notifications@github.com>)> schrieb:
	Can you provide any logs?
I think it switches to inactive when exception in the app occurs.

**Comment by mlojewski-me** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html

**Comment by Saliman-Banana** [comment]
Hello, Marcin,

it took some time until the error occurred again, but between yesterday and today the app was inactive again.
I have attached the logfile of Nextcloud

Best regards
Martin
15. Oktober 2019 08:36, "Marcin Łojewski" <notifications@github.com (mailto:notifications@github.com?to=%22Marcin%20%C5%81ojewski%22%20<notifications@github.com>)> schrieb:
	https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html (https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html)

**Comment by mlojewski-me** [comment]
I don't see any logs?

**Comment by Saliman-Banana** [comment]
Hello Marcin,

I added the log as 7zip file.
Alternatively also the link to the share:
https://webtransfer.musicandsales.com/s/gzmc2zx9o5YR4BR (https://webtransfer.musicandsales.com/s/gzmc2zx9o5YR4BR)

Thank you
Martin
14. November 2019 09:37, "Marcin Łojewski" <notifications@github.com (mailto:notifications@github.com?to=%22Marcin%20%C5%81ojewski%22%20<notifications@github.com>)> schrieb:
	I don't see any logs?

**Comment by mlojewski-me** [comment]
Still link is inactive can you paste log in this thread ?

**Comment by Saliman-Banana** [comment]
Hello,
I have changed employers, so the problem is no longer relevant to me. But I still noticed that the app is inactive when the AD controller was not reachable. Although it should be independent.
