### ISSUE TITLE
Documentation is misleading about password salting support

### ISSUE THREAD

**Issue by numero-six** [nextcloud/user_sql#114]
[`README.md` for version 4.3](https://github.com/nextcloud/user_sql/tree/v4.3.0#hash-algorithms) tells that for `SHA-1` that "No salt supported".

It's misleading because the app just works fine with a column storing the salt, and another storing the `sha1($password . $salt)`.

Since my database use sha1 + salt appending, at first I thought I couldn't use this app but I was wronged: it works just fine.

I guess other lines from that table are wrong too.

**Comment by mlojewski-me** [comment]
Yes. You are right. I guess after adding salt feature I forget to update this table.
Thanks for letting me know.
The table is updated.
https://github.com/nextcloud/user_sql/commit/b7a7ede706efb479f7660c10ef02a53b85a844ea
