### ISSUE TITLE
Can we expect maxversion= 17 soon?

### ISSUE THREAD

**Issue by jfey** [nextcloud/user_sql#116]
Hello,

I like to integrate user_sql in a new NextCloud 17 setup to be able to connect a user microservice with NextCloud, but currently this is not possible via the official app store.

Is an official release planned (maxversion=17) for the near future or should i install it via direct install in the meantime? Any issues to be expected this way?

thanks for the efforts 

cheers

Juergen

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/ce09d8e5e12a0d16556e6d7e6baeab8334d81e9d
I'm going to merge code to master and release a new version when I look and solve reasonable issues.

**Comment by johnwmail** [comment]
> [ce09d8e](https://github.com/nextcloud/user_sql/commit/ce09d8e5e12a0d16556e6d7e6baeab8334d81e9d)
> I'm going to merge code to master and release a new version when I look and solve reasonable issues.

May we know, what issues do you want to solve, before release a new version?

**Comment by mlojewski-me** [comment]
I wanted to solved the following issues 
https://github.com/nextcloud/user_sql/milestone/4
but after further thought I decided to release it now and move these issues to next release.
