### ISSUE TITLE
Does this work with pgsql bf encrypted passwords?

### ISSUE THREAD

**Issue by zwoggel** [nextcloud/user_sql#118]
Hi,

just a quick question:
I'm using the postgres crypt() function with Blowfish (variant 2a) algorithm to encrypt the passwords in the DB (see https://www.postgresql.org/docs/11/pgcrypto.html#id-1.11.7.34.6).
Does the App work with those out of the box? If not, would it be possible to add support for it?

Thanks and best regards!

**Comment by mlojewski-me** [comment]
It works, try Blowfish (Crypt).
