### ISSUE TITLE
App is spamming NC log

### ISSUE THREAD

**Issue by zwoggel** [nextcloud/user_sql#119]
Hi,

after clearing my earlier question about the pgsql crypt (thanks for that!), I enabled and configured the App and instantly noticed a massive spam of Debug log entries sayig "The application properties has been loaded." in the NC log. The same entry is generated pretty much every second.

![nc_log](https://user-images.githubusercontent.com/22392919/66574012-d3e0c400-eb73-11e9-9247-7034b43cf19d.JPG)

I'm currently on NC 17

**Comment by mlojewski-me** [comment]
First of all it's debug level so it should not be set on production.
What cause these messages is that when log page is refreshed, configuration gets loaded.
First solution is to turn off live refreshing, second is to turn on cache in option panel of this plugin, in that case configuration will be taken from cache, and won't be loaded at every request.
