### ISSUE TITLE
"Object of class Closure could not be converted to string" during cronjobs

### ISSUE THREAD

**Issue by errror** [nextcloud/user_sql#120]
Which every invocation of /cron.php, I get the following message in my logs:

{PHP} Object of class Closure could not be converted to string at /cloud/nextcloud/apps/user_sql/lib/Backend/UserBackend.php#481

Please try to check if this message/warning can be avoided or muted.

Best,

Patrick

**Comment by mlojewski-me** [comment]
I see what can cause it.
Can you tell me what version of app do you use?

**Comment by errror** [comment]
User and Group SQL Backends Version 4.4.0 on Nextcloud 16.0.5 with PHP 7.3.9-1~deb10u1 on Debian/buster.

**Comment by dphi** [comment]
Im seeing the same with user_sql 4.4.0 and nextcloud 17 with php 7.3.10

**Comment by peti2000** [comment]
same issue here. php 7.2.23 nextcloud 16.0.5 user_sql 4.4.0

**Comment by errror** [comment]
After upgrading to nextcloud 17, the message format changed:
{"reqId":"HxK9Fd0s8oeb1UwFsvlh","level":3,"time":"2019-11-20T22:45:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Object of class Closure could not be converted to string at \/cloud\/nextcloud\/apps\/user_sql\/lib\/Backend\/UserBackend.php#481","userAgent":"--","version":"17.0.1.1"}

Could you please fix this? Thanks!

**Comment by mlojewski-me** [comment]
Fixed in 4.4.1
