### ISSUE TITLE
Add UUID table column

### ISSUE THREAD

**Issue by palmtown** [nextcloud/user_sql#121]
Hello,

Can you add a UUID table column in Admin >> Settings >> SQL Backends >> User Table >> Columns so that I can differentiate between the UUID and the Username?  Currently, your app assumes the Username is always the UUID.  However, in many cases, the email is used for login, however, their unique primary key is their UUID.  

Reason being is that if I use email column as username, and a user change their email address, then their data will be lost (disconnected) when they login under new username (email).

This appears to be the same issue as https://github.com/nextcloud/user_sql/issues/108.

**Comment by palmtown** [comment]
Hello,

I resolved this issue with pull request https://github.com/nextcloud/user_sql/pull/122.  Please apply!

**Comment by mlojewski-me** [comment]
fixed with https://github.com/nextcloud/user_sql/issues/108
