### ISSUE TITLE
Critical Error: Duplicate entry '000DDD32-6FE6-45C0-8AEF-AAAAAAAA' for key 'PRIMARY'

### ISSUE THREAD

**Issue by palmtown** [nextcloud/user_sql#123]
Hello,

I noticed that if Name sync or Email sync are set in Admin >> Settings >> SQL Backends >> Options to "SQL always wins" and the users do not exists in the database, an exception **Duplicate entry '000DDD32-6FE6-45C0-8AEF-AAAAAAAA' for key 'PRIMARY'** is generated when I browse to Admin >> Users.

If I "SQL always wins" for quota, there is no issue as it is stored in a different table.

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '000DDD32-6FE6-45C0-8AEF-AAAAAAAA' for key 'PRIMARY'",{"errorInfo":["23000",1062,"Duplicate entry '000DDD32-6FE6-45C0-8AEF-AAAAAAAA' for key 'PRIMARY'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["23000",1062,"Duplicate entry '000DDD32-6FE6-45C0-8AEF-AAAAAAAA' for key 'PRIMARY'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'INSERT INTO `oc_accounts` (`uid`, `data`)....

**Comment by jonmert** [comment]
Same here:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_accounts` (`uid`, `data`) VALUES(?, ?)' with params ["mmustermann", "{\"displayname\":{\"value\":\"Max Mustermann\",\"scope\":\"contacts\",\"verified\":\"0\"},\"address\":{\"value\":\"\",\"scope\":\"private\",\"verified\":\"0\"},\"website\":{\"value\":\"\",\"scope\":\"private\",\"verified\":\"0\"},\"email\":{\"value\":\"mmustermann@test.de\",\"scope\":\"contacts\",\"verified\":\"0\"},\"avatar\":{\"scope\":\"contacts\"},\"phone\":{\"value\":\"\",\"scope\":\"private\",\"verified\":\"0\"},\"twitter\":{\"value\":\"\",\"scope\":\"private\",\"verified\":\"0\"}}"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mmustermann' for key 'PRIMARY'

**Comment by jonmert** [comment]
If I set Options to "Sync only ones" the error occurs, too.

**Comment by jonmert** [comment]
If Email sync Option set to "None" or "Nextcloud always wins", the error does not occur. 

Possible related to #136

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/d6cbc24dad48b8e5bfa30b1f4c80cc060a365ffc
