### ISSUE TITLE
WEBDAV error + Object of class Closure could not be converted to string at /var/www/clients/client1/web4/web/apps/user_sql/lib/Backend/UserBackend.php#481

### ISSUE THREAD

**Issue by peti2000** [nextcloud/user_sql#126]
I cant use nextcloud client or any webdav client + I have an error:
`Object of class Closure could not be converted to string at /var/www/clients/client1/web4/web/apps/user_sql/lib/Backend/UserBackend.php#481`
nextcloud v16.0.5 user_sql 4.4.0

**Comment by mlojewski-me** [comment]
Fixed in 4.4.1
