### ISSUE TITLE
How to configure it to work with Postgresql

### ISSUE THREAD

**Issue by pauldeng** [nextcloud/user_sql#13]
Hi,

Really appreciate your work!

Issue:
user_sql can not work with Postgresql.

Description:
user_sql works fine with MySQL. However, when I configure it to work with Postgresql, it can connect to the db but does not list any tables. If I manually enter the table name, it complains cannot find it. Please check the screencast: https://youtu.be/imTSNCCVLEY

Here is my configuration:
- OS: Ubuntu 16.04
- NextCloud: 12.04
- user_sql: 2.4 ( git version c6956d24af7840b1c1f87343d6d1d481e6dcc33f)
- postgresql: 9.5
- Browser: firefox 57

I would love to contribute and make a better document.

Thanks a lot!
Merry Xmas and Happy New Year!

Cheers,
Paul

**Comment by mlojewski-me** [comment]
Can You check this version: https://github.com/nextcloud/user_sql/tree/v2.3.2-nc12? I use this one along with PostgreSQL 9.6 and everything works fine for me?

**Comment by mlojewski-me** [comment]
Or try to set parameters with occ command for example:
  ```
occ config:app:set user_sql "col_active_default" --value="active"
  occ config:app:set user_sql "col_displayname_default" --value="full_name"
  occ config:app:set user_sql "col_email_default" --value="email_address"
  occ config:app:set user_sql "col_password_default" --value="password_hash"
  occ config:app:set user_sql "col_username_default" --value="username"
  occ config:app:set user_sql "set_crypt_type_default" --value="joomla2"
  occ config:app:set user_sql "set_mail_sync_mode_default" --value="forcesql"
  occ config:app:set user_sql "sql_database_default" --value="database"
  occ config:app:set user_sql "sql_driver_default" --value="pgsql"
  occ config:app:set user_sql "sql_hostname_default" --value="localhost"
  occ config:app:set user_sql "sql_password_default" --value="passwd"
  occ config:app:set user_sql "sql_table_default" --value="table"
  occ config:app:set user_sql "sql_username_default" --value="nextcloud"
```

**Comment by pauldeng** [comment]
Hi, 

Tried 2 setups, none of them work.
- Setup 1: user_sql 2.4 + pgsql 10.1, same issue described before. https://youtu.be/7jhe3PIFWgc
- Setup 2: user_sql 2.3.2-nc12 + pgsql 9.6, same issue described before. https://youtu.be/lBV2vr7mIT0

I have not got time to test occ command.

Thanks a lot.

**Comment by mlojewski-me** [comment]
I will try to reproduce your error and fix it later. For now you can use occ command it should work (it works for me).

**Comment by pauldeng** [comment]
Tested occ comand, it works.

Here is what i did:
sudo -u www-data ./occ config:app:set user_sql "sql_hostname_default" --value="localhost"
sudo -u www-data ./occ config:app:set user_sql "sql_driver_default" --value="pgsql"
sudo -u www-data ./occ config:app:set user_sql "sql_database_default" --value="user_management"
sudo -u www-data ./occ config:app:set user_sql "set_crypt_type_default" --value="cleartext"
sudo -u www-data ./occ config:app:set user_sql "sql_table_default" --value="public.users"
sudo -u www-data ./occ config:app:set user_sql "sql_username_default" --value="postgres"
sudo -u www-data ./occ config:app:set user_sql "sql_password_default" --value="passwd"
sudo -u www-data ./occ config:app:set user_sql "sql_password_default" --value="POSTGRES_USER_PASSWORD"
sudo -u www-data ./occ config:app:set user_sql "col_password_default" --value="password"
sudo -u www-data ./occ config:app:set user_sql "col_username_default" --value="username"

Or these data can be added by pgadmin4 in table oc_appconfig in nextcloud database.

Thanks a lot for your support and have a great day!

Cheers,
Paul

**Comment by mlojewski-me** [comment]
This commit fixed this issue:
https://github.com/nextcloud/user_sql/commit/105f5b67624365b15a7302e6be0d3f4d8e9827f4
