### ISSUE TITLE
Documenting cache #question

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/user_sql#131]
I connected wordpress (and civicrm) with my nextcloud instance by your app. The user get created in wordpress, and I send an email with an explaination do reset the password to that person.

So they reset their password and log in to nextcloud immediately after that. Question is: Is it safe to activate cache in your app, how often is it cleared?

**Comment by mlojewski-me** [comment]
TTL for cache is 1 hour.
It is not used in auth process, so every time user authenticates password hash is retrieved from database.
When user/group data is not found in cache database is queried.
