### ISSUE TITLE
Error connecting to the database: Failed to connect to the database: An exception occurred in driver: could not find driver

### ISSUE THREAD

**Issue by Lihaes** [nextcloud/user_sql#132]
Hi, 

I have a fresh install ver 18 on a ubuntu18.04 and when trying to verify the DB-Settings I get the error:

`Error connecting to the database: Failed to connect to the database: An exception occurred in driver: could not find driver`

Thanks and best regards

**Comment by mlojewski-me** [comment]
The message clearly say what you are missing.
Try to install driver for example for debian it is:
https://packages.debian.org/sid/php7.4-mysql
https://packages.debian.org/stretch/php-pgsql
