### ISSUE TITLE
SHA512 (CRYPT) Options doesn't work with doveadm passwords

### ISSUE THREAD

**Issue by Lihaes** [nextcloud/user_sql#133]
Hi,

if I create an password via `doveadm -s SHA512-Crypt` I get an result like this:

`{SHA512-CRYPT}$6$t4JfU2FvdynK4x2h$K5vD/0sy2nt.................Z/SkkHhiAzfXd`

Unfortunately, your value looks slightly different:

`$6$rounds=5000$yH.Q0OL4qbCOUJ3q$Xry5EVFva3wKnfo8/ktrugmBd8tcl34NK6rXInv1HhmdSUNLEm0La9JnA57rqwQ.9/Bz513MD4tvmmISLUIHs/`

Is there a chance to support this?

Best regards

**Comment by mlojewski-me** [comment]
Have you checked if it is compatible?
I can add option like prepend scheme name if it's not to crypt algorithms.

**Comment by mlojewski-me** [comment]
It's 'SHA512 (Crypt)' it is possible the make a view which cuts `{SHA512-CRYPT}` part.

**Comment by einalex** [comment]
the manipulating view prevents people from updating their passwords though.
