### ISSUE TITLE
Login with email failed

### ISSUE THREAD

**Issue by officialjuhoo** [nextcloud/user_sql#135]
Hello,
If a user creates an account on my website, then he cannot log on to nextcloud with his email only with his user name. How can i change this??

Please help me!

All best,
Alex

**Comment by mlojewski-me** [comment]
It's is not possible yet, it has to be developed.
Right now the only choice I see is to set uid column to email address column, but it has to be tested.

**Comment by officialjuhoo** [comment]
Yes, but then my users can no longer log in with their username, only with email. I've already tried that.
When will the plugin be updated?

**Comment by mlojewski-me** [comment]
I will try to do this this weekend :)

**Comment by officialjuhoo** [comment]
Thank you a lot!!!! You are the best! :)

**Comment by mlojewski-me** [comment]
Done in https://github.com/nextcloud/user_sql/commit/953dae293e754431fd540832c602a398a13dac93
Next week I will try to release new version.
