### ISSUE TITLE
After adding user in backend --> Error in Users (Everyone)

### ISSUE THREAD

**Issue by jonmert** [nextcloud/user_sql#136]
Hi,

after adding adding a new user in the sql backend, the Everyone Page in Users throws an error. The problems resolves after a refresh of the page. 
If adding 5 Users, you have to refresh 5 times.
![2020-04-03_103944](https://user-images.githubusercontent.com/17846375/78341635-51701480-7598-11ea-98d5-037e47a9a11b.jpg)

Kind regards
Jonas

**Comment by jonmert** [comment]
Hi,

just figured out the issue is not occurring, when E-Mail sync is set to "None" or "Nextcloud always wins".

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/d6cbc24dad48b8e5bfa30b1f4c80cc060a365ffc
duplicated https://github.com/nextcloud/user_sql/issues/123
