### ISSUE TITLE
Hash algorithm for Joomla doesn't work

### ISSUE THREAD

**Issue by alexmusses** [nextcloud/user_sql#140]
The normal Hash algorithm for Joomla "Joomla MD5 Encryption" doesn't work.
Also the Hash algorithm from wiki of this article (Blowfish) doesn't work.

**Comment by mlojewski-me** [comment]
can you give me an example hash?

**Comment by alexmusses** [comment]
The passwort "secret" is: "d2064d358136996bd22421584a7cb33e:trd7TvKHx6dMeoMmBVxYmg0vuXEA4199" without ""
Joomla says it is MD5 and salted hashed password
