### ISSUE TITLE
App class OCA\\UserSQL\\AppInfo\\Application is not setup via query() but directly

### ISSUE THREAD

**Issue by edvanleeuwen** [nextcloud/user_sql#152]
I have been seeing some entries in the nextcloud.log file:
`App class OCA\\UserSQL\\AppInfo\\Application is not setup via query() but directly`

This does not seem to cause any problems. Could this be a php 7.4 incompatibility?

**Comment by mlojewski-me** [comment]
https://help.nextcloud.com/t/many-apps-with-runtimeexception-is-not-set-up-via-query-but-directly-after-17-0-3-upgrade-to-18-0-0/70387
