### ISSUE TITLE
NC20 Version

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/user_sql#153]
Do you think the current version will work with NC20 even it's said missing updates for that app?

**Comment by dregad** [comment]
Well I tried the update and the authentication does not work anymore :cry:

**Comment by Dubidubiduu** [comment]
> 
> 
> Well I tried the update and the authentication does not work anymore 😢

I also did, but it works for my existing user accounts (I guess), at least it works for my very own account.

I do have problems with new accounts or maybe it's just my testing environment.

Have you tried login by username? For one account first login by email wasn't possible, but it worked with username.

Now login with mail also works.

**Comment by dregad** [comment]
I did try to access by username, but login failed for all the remote accounts. I could only login with a "local" user.

**Comment by jeltevdw** [comment]
Is it still planned to make this application compatible with NC20?

**Comment by roberthr74** [comment]
Is this abandoned extension? Can't update to NC20 since I need this.

**Comment by gitterfeuer** [comment]
I update to NC20 and I can still login.

**Comment by yward** [comment]
I'll try to setup a test server and test this when I have time, I'll post the results here.
Cannot test on my production server sadly.

**Comment by tobox** [comment]
Any updates on this? I see some changes in the development branch to allow installation on NC20, but can anybody confirm that it works?

**Comment by Dubidubiduu** [comment]
> 
> 
> Any updates on this? I see some changes in the development branch to allow installation on NC20, but can anybody confirm that it works?

works for me

**Comment by jeltevdw** [comment]
> Any updates on this? I see some changes in the development branch to allow installation on NC20, but can anybody confirm that it works?
I did a test in a test env. Running in NC19, upgraded to dev branch. It forces a database upgrade for this plugin. This seems to work fine. Then upgraded the test env to NC20, working fine, users where still able to login and access to group folders seems to be ok. After these checks I upgraded my production environment. No issues so far.

**Comment by mlojewski-me** [comment]
Done
https://apps.nextcloud.com/apps/user_sql/releases?platform=20#20
The app will not work in NC21 because Doctrine DBAL has been updated to version 3.0.0, so it needs more code changes

**Comment by dregad** [comment]
@mlojewski-me many thanks for fixing this.

> The app will not work in NC21 because Doctrine DBAL has been updated to version 3.0.0, so it needs more code changes

Is this something you plan to implement, or will user_sql support end with NC20 ?

**Comment by mlojewski-me** [comment]
I'm going to make the changes but I need time

**Comment by dregad** [comment]
Great, thank you very much. No rush :smile:

**Comment by leuedaniel** [comment]
> I'm going to make the changes but I need time

Can we spend something for this change?
