### ISSUE TITLE
Issue configuring synchronization

### ISSUE THREAD

**Issue by ibboliver** [nextcloud/user_sql#157]
Hi there!

First of all, thanks for this great NC app!

I'm using this app the first time. I setup the database connection and the table names for user, groups and usergroup. Initially I set _Name sync_ and _Email sync_ to _Syncronise only once_. After saving, all my users and user-group relations are correctly imported into nextcloud. I checked that by successfully logging in with one of my users (_my_ means my peer SQL database).

The other way around I have two problems (for now :wink:):

- When creating new users, they do not appear in my SQL database
- I cannot add my usergroups to users, the entries are grayed out

Am I wrong expecting this app working in this direction? If not, where can I find logs or get some informations for troubleshooting? 

My installation details: 
NC 20.0.7
App version 4.6.0

Here are the current settings:

![Bildschirmfoto von 2021-03-25 10-49-43](https://user-images.githubusercontent.com/7429390/112453302-d929d280-8d57-11eb-950f-0e03e6f6de8a.png)

![Bildschirmfoto von 2021-03-25 10-48-36](https://user-images.githubusercontent.com/7429390/112453316-dc24c300-8d57-11eb-8df6-a7d60473436d.png)

Regards,
Oliver

**Comment by mlojewski-me** [comment]
I think the problem is that database is treated as readonly, write operations are not implemented

**Comment by ibboliver** [comment]
> I think the problem is that database is treated as readonly, write operations are not implemented

Sorry, I'm not sure if I understand you right. Do you mean write operations are generally not supported by user_sql app or is this a feature that must be enabled somewhere?

**Comment by mlojewski-me** [comment]
Yes, it's not supported and won't be because it would take much time to implement, The main purpose of the plugin is to allow users from external database source to log in.

**Comment by ibboliver** [comment]
Ahh, ok. So I just misunderstood that. Thanks!
