### ISSUE TITLE
Nextcloud 22 support?

### ISSUE THREAD

**Issue by tobox** [nextcloud/user_sql#163]
The only addon that prevents me from updating to nextcloud 22 is user_sql. 

Is this project dead or can we expect an update?

Regards

**Comment by nanoflow** [comment]
Nextcloud 22 works for me (activated as untested app) Only problem is the user email that is not synced anymore

**Comment by tobox** [comment]
My instance is too critical to just give it a shot and hope it does not blow up. I guess I will wait for a few more weeks and then convert my user_sql setup to ldap.

**Comment by martinschniewind** [comment]
Unfortunately upgraded nextcloud to 22 without checking if user_sql will be working.
So I am - again - in urgent need for an upgrade. Willing to spend 50 €.
Thanks in advance
Martin

**Comment by mlojewski-me** [comment]
I will look at it, I have different priorities right now and I don't have time to maintain this plugin like I used to.
If it doesn't involve any major changes I will release a new version this weekend.

**Comment by mlojewski-me** [comment]
Done https://apps.nextcloud.com/apps/user_sql/releases?platform=22#22
If you want you can donate here: https://paypal.me/mlojewskime
I need to find more time to look at all issues :)

**Comment by tobox** [comment]
Great news, it works perfectly again. Thanks a lot!
