### ISSUE TITLE
Not an issue - usage query!

### ISSUE THREAD

**Issue by dansmithpm** [nextcloud/user_sql#17]
In principle this looks great though just can't work out how to use it! My understanding is that it allows users to login via an external authorisation table which is exactly what I was looking for!

I've installed and enabled the app and on the admin console I've setup the default domain with my database and user table. All settings are verified but nothing happens. I've set as SQL wins on the tab which I understand to mean that the external database is always more current.

The only thing I need to query in my setup is the field for user active column - what sort of field does this expect and what value does it expect. At present I've got a varchar(1) which is either Y or null so don't know if this is why nothing appears to be happening?

Any help much appreciated as this plugin is the missing piece of my puzzle!

**Comment by poVoq** [comment]
Not sure I understand the question.
"User Active Column" setting is not required. In my settings it is blank.

Did you set the "Real Name Column" though? I previously didn't set that and had issues. If that doesn't exist in your external database, just use the same value as in your "Username Column" as a work around.

Maybe this is a bug in sql_user?

**Comment by dansmithpm** [comment]
First off I've got nextcloud 12.0.4 installed in a shared hosting environment running with userdata stored in Amazon S3 bucket - all works very nicely. I'm trying to have this now setup so that my primary database (also on the same shared sever) can be used for user login to nextcloud so I don't have to try to replicate users or cope with updating with password changes etc.

So I have a user table in my other database tblUsers where the relevant fields are as follows

uEmail	varchar(100)	- the email address of the user 
uPass	varchar(255)	- their password sha1 format
uName	varchar(255)	- their full name

I put database details on first tab and verifies ok

second tab per the screenshot here which I believe is fine
![image](https://user-images.githubusercontent.com/35139119/34643679-4b84af2e-f320-11e7-9efe-1bc9bae4648b.png)

Email settings tab per below
![Uploading image.png…]()

So all seems fine.

The expected behaviour is that from the nextcloud login screen I can enter a userid and password from my other database and it will authenticate through to the nextcloud instance, though just gives wrong password. Then again if I enter anything in userid and password other than a valid nextcloud created user it gives the same message?

**Comment by dansmithpm** [comment]
got it working, used occ app:enable rather than use the admin console and it seems to have worked. also needed to set 'auth.bruteforce.protection.enabled' => false,
