### ISSUE TITLE
Drupal authentication

### ISSUE THREAD

**Issue by WardinT** [nextcloud/user_sql#24]
I have added user authentication against a Drupal 7 database as described here in the README. Not knowing if this may be helpful to others, I attach the changed files instead of committing them. If however, that would be included in future releases, I'd be happy.
[usr_sql.drupal.zip](https://github.com/nextcloud/user_sql/files/1716041/usr_sql.drupal.zip)

**Comment by mlojewski-me** [comment]
Can You make a pull request? This is the way we process code changes.

**Comment by WardinT** [comment]
Tried to but as a git newbie, I didn't manage to.

**Comment by WardinT** [comment]
Finally managed to create the pull request.
