### ISSUE TITLE
vbulletin users and nextcloud

### ISSUE THREAD

**Issue by deniskril** [nextcloud/user_sql#26]
Hello, i have vbulletin 4 and nextcloud 13
i installed sql user backend
users are appear in nextcloud but cant auth in nextcloud.

Please help

**Comment by mlojewski-me** [comment]
I guess there could be something wrong with the hash algorithm you use.
Have you check logs, if any errors appeared there?

**Comment by deniskril** [comment]
vbulletin 4 use md5 + salt encription
this algorithm possible in your plugin?

**Comment by deniskril** [comment]
password in db looks like 225c05b3ff050a1a2063894556042415

**Comment by deniskril** [comment]
not working(

**Comment by deniskril** [comment]
how can i clear imported users and connection settings?

**Comment by mlojewski-me** [comment]
Disable the app

**Comment by deniskril** [comment]
i change db in settings and disable, after i enable and old user is appear

**Comment by poVoq** [comment]
I think you need to disable and remove.

**Comment by mlojewski-me** [comment]
If you enable the app it is correct that you see these users if you don't want use the app just disable it and remove from filesystem.
