### ISSUE TITLE
[Request] Where clauses

### ISSUE THREAD

**Issue by lyn1337** [nextcloud/user_sql#28]
Hej,

I'd find it nice to see being able to apply where clauses to the user / password column settings.

In my case I have a 'value' field which only holds the password, if a 'store' field says 'accounts'.

**Comment by mlojewski-me** [comment]
You can use database view instead I don't see the reason to implement this functionality.
https://dev.mysql.com/doc/refman/5.7/en/views.html
https://www.postgresql.org/docs/10/static/tutorial-views.html
