### ISSUE TITLE
Nextcloud 14 will drop OCP\JSON support

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_sql#29]
Hi @mlojewski-me, `OCP\JSON` is deprecated since version 8.1 and will run into the 3 year deprecation time soon. With the upcoming Nextcloud 14 this will not be available anymore. We highly encourage you to move over from those manual checks in the files in `ajax/` to the AppFramework way of writing methods. This then takes care of all the checks that are provided by `OCP\JSON` out of the box. If you need help with the migration please reach out to us. The AppFramework was introduced in version 7.

The removal PR: https://github.com/nextcloud/server/pull/8943
A PR that shows how to move from the `ajax/` files to AppFramework: https://github.com/nextcloud/server/pull/8800

**Comment by mlojewski-me** [comment]
Thanks for the info.
I work on a new version in develop branch but I still need some time to finish it.
I plan to rewrite the whole application to follow the clean code and newest Nextcloud API.
I think I need maximium of one month to release the new version for testing.

**Comment by MorrisJobke** [comment]
> I think I need maximium of one month to release the new version for testing.

Don't worry - Nextcloud 14 will take some months from now ;) We just want to give some heads up on upcoming changes, so that app developers can adjust their code. ;)

**Comment by MorrisJobke** [comment]
> .
> Don't worry - Nextcloud 14 will take some months from now ;) We just want to give some heads up on upcoming changes, so that app developers can adjust their code. ;)

Once we know more you can read it in https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Alone the feature frees phase will be one month roughly.

**Comment by mlojewski-me** [comment]
New version has been released.
