### ISSUE TITLE
Update the app store!

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/user_sql#3]
I understand the app is updated for Nc 11 and 12, would be great to upload the new versions to the app store!

**Comment by poVoq** [comment]
This a fork, so I guess it would need to be submitted under a different name?

**Comment by MariusBluem** [comment]
I have moved this now to nextcloud/user_sql and we will talk to the former contributor, so that we can re-publish that as "user_sql" without changing the name :) @mlojewski-me @andyboeh

**Comment by MariusBluem** [comment]
See: https://nextcloudappstore.readthedocs.io/en/latest/developer.html#transferring-your-app-to-a-new-owner for the App Store ;)

**Comment by andyboeh** [comment]
It should be possible to transfer the app now!

**Comment by mlojewski-me** [comment]
@MariusBluem Should I issue a new key or @andyboeh can you send me the current one?

**Comment by MariusBluem** [comment]
@andyboeh @mlojewski-me Have you both exchanged the key now? If not, maybe @MorrisJobke is able to revoke the current user_sql cert, and issue a new one. I don't want to have something like `user_sql2` in the appstore 😅

**Comment by andyboeh** [comment]
No, we haven't. IMHO it's not a good idea to send private keys around (and I can't find it anyway).

**Comment by MorrisJobke** [comment]
> No, we haven't. IMHO it's not a good idea to send private keys around (and I can't find it anyway).

Then encrypt them with @mlojewski-me's public pgp key and send it encrypted over to him.

**Comment by MariusBluem** [comment]
> and I can't find it anyway

Sounds like "lost" -> revoke -> new key for @mlojewski-me 🍾😝

**Comment by mlojewski-me** [comment]
So I will commit a new CSR in [user_sql](https://github.com/nextcloud/app-certificate-requests/tree/master/user_sql)

**Comment by mlojewski-me** [comment]
Done.
https://apps.nextcloud.com/apps/user_sql
