### ISSUE TITLE
Cannot enable

### ISSUE THREAD

**Issue by ozzi-** [nextcloud/user_sql#30]
Hi 

Unfortunately I cannot enable user_sql using a fresh install of 13.0.1..
Any ideas?
![image](https://user-images.githubusercontent.com/7944573/38508042-68cba744-3c1e-11e8-926d-b1c93e14ad4e.png)
Log:
![image](https://user-images.githubusercontent.com/7944573/38508793-6bbe9630-3c20-11e8-8a8e-a322241f0dd2.png)

Cheers

**Comment by gpgmailencrypt** [comment]
You probably use sqlite as database. Only mysql and postgres are supported
