### ISSUE TITLE
you have an error in you sql syntax

### ISSUE THREAD

**Issue by Zjemm** [nextcloud/user_sql#31]
Hi I'm trying to get the SQL backend working for Nextcloud 13. While the login is succesfull i get an error right after logging in:

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details
Remote Address: 10.1.0.1
Request ID: pEmI5rzxuK55vseLl0cn
 
in the nextcloud log itself i got to see:

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT FROM virtual_users WHERE email = :uid' with params ["john@example.org"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM virtual_users WHERE email = 'john@example.org'' at line 1

/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT FROM vi...', Array)
/var/www/html/nextcloud/apps/user_sql/lib/helper.php - line 218: Doctrine\DBAL\Statement->execute()
/var/www/html/nextcloud/apps/user_sql/lib/user_sql.php - line 594: OCA\user_sql\lib\Helper->runQuery('getDisplayName', Array)
/var/www/html/nextcloud/lib/private/User/User.php - line 120: OCA\user_sql\OC_USER_SQL->getDisplayName('john@example.or...')
/var/www/html/nextcloud/lib/private/legacy/helper.php - line 603: OC\User\User->getDisplayName()
/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 131: OC_Helper getStorageInfo('/', Object(OC\Files\FileInfo))
/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 160: OCA\Files\Controller\ViewController->getStorageInfo()
[internal function] OCA\Files\Controller\ViewController->index('', '', NULL, false)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/apps/files/')
/var/www/html/nextcloud/index.php - line 37: OC handleRequest()
{main}

Any idea how to solve this?
Can i deliver extra information, just let me know

Zjemm

**Comment by mlojewski-me** [comment]
I guess you missed a column in your configuration. Check if all necessary column names are set.

**Comment by Zjemm** [comment]
Great! thats it :) 
thank you

the field should me mandetory :P
