### ISSUE TITLE
Additional field for numeric userid to link with groups?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#32]
Hello,

I am trying to link my Tikiwiki system to Nextcloud, but the problem I have is that in Tiki every user has a login name and a separate numeric userid. Thus by putting the login as the username column, I seem to be able to get the log-in working. But the groups are identified by the numeric userid and thus I can't link them to the login name in the current system.

Thanks for looking into it.

**Comment by poVoq** [comment]
Sorry, but where can I put that into the settings? I am aware of such SQL queries, but the settings interface of user_sql doesn't seem to allow doing that?

**Comment by mlojewski-me** [comment]
It's a database engine feature:
https://dev.mysql.com/doc/refman/5.7/en/create-view.html
https://www.postgresql.org/docs/9.4/static/sql-createview.html
Right now I don't see any other option.
You should consult someone who knows databases.
I think if you develop a system basic database knowledge is necessary.

**Comment by poVoq** [comment]
Ok, thanks! Will look into it.

**Comment by poVoq** [comment]
For future reference for hosts that don't allow direct command-line access to mysql, but have phpmyadmin:
https://www.404techsupport.com/2012/04/12/creating-and-editing-views-in-phpmyadmin/
