### ISSUE TITLE
User_sql break group sharing when app activity is enabled

### ISSUE THREAD

**Issue by ulukyn** [nextcloud/user_sql#33]
Since user_sql apps don't manage limit and offset in **usersInGroup** function:
`$rows = $this -> helper -> runQuery('getGroupUsers', array('gid' => $gid), false, true);`

The unshareFromGroup function of **Activity** app start a infinity loop : 
```
while (!empty($users)) {
			$this->addNotificationsForGroupUsers($users, 'unshared_by', $share->getNodeId(), $share->getNodeType(), $share->getTarget(), $share->getId());
			$offset += self::USER_BATCH_SIZE;
			$users = $group->searchUsers('', self::USER_BATCH_SIZE, $offset);
}
```

to fix that, just add offset and limit params to runQuery : 
``` 
$rows = $this -> helper -> runQuery('getGroupUsers', array('gid' => $gid), false, true, ['limit' => $limit, 'offset' => $offset]);
```

**Comment by mlojewski-me** [comment]
Done.
Thanks for advise.
