### ISSUE TITLE
Wordpress: how fill "UserGroups"?

### ISSUE THREAD

**Issue by Peronia** [nextcloud/user_sql#38]
Hi,

I've installed nextcloud and this addon. I've activated and configurated it.
When I try to login use my Wordpress login it say "Wrong password" all the times.
But in WP the password is correct.
I choose your recommended settings.

To test I've changed the encrypten method to "cleartext" and place a clear password in the database. Same problem.

Edit: It seems to be a problem if the group settings were not configurated. The log says:
`Undefined index: groupTable at /var/www/virtual/test/html/nextcloud/apps/user_sql/ajax/settings.php#228`
So im looking into wordpress codex where the userlevel are stored:
https://codex.wordpress.org/Database_Description#Table_Overview
Finally in wp_usermeta I've found the wp_user_level in the column meta_key. But the options here mixed so I cant configure it in you app.

**Comment by mlojewski-me** [comment]
Can you set the log level to debug and give us these logs from auth failure?

**Comment by Peronia** [comment]
I've edited my previous post. The log says the option getUserGroups cant find an entry.

**Comment by mlojewski-me** [comment]
The mention error is generated when you try to save settings. It has nothing to do with the authentication problem. Can you send your app configuration and user row from wp database?

**Comment by Peronia** [comment]
Here is your row from WP. I change the username and password.
`INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(4, 'user1', '654625346435565', 'niceUser', 'foo@bar.vgi', '', '2016-05-16 17:48:53', '', 0, 'Niceo'),`

I've take pictures from the config of your app in my nextcloud. I don't know where I can attach it here.
Download: https://cloud.finnex.info/index.php/s/FR3MbTQEmGkqR74

**Comment by mlojewski-me** [comment]
user_status is 0 that means account is inactive. Set invert active value checkbox. Also the password you use in not hash with chosen algorithm

**Comment by Peronia** [comment]
As I wrote above, I changed the password. In real its the hash from WP.
In my case your solution with the invert checkbox solved the problem. Now all works fine, thanks.
You sluold explain that a little bit more in the descriptiontext under the box.
