### ISSUE TITLE
Error The selected SQL table does not exist!

### ISSUE THREAD

**Issue by Alejandro888** [nextcloud/user_sql#39]
Hi Im useing nextcloud 13.0.3
I`ve install the plugin and try to config.
first it give me Successfully connected to database, then if I want to save the The selected SQL table does not exist! apper. It it the same with The selected SQL table wp_users does not exist!
Im a little noob, so please advice. Thank you

**Comment by poVoq** [comment]
If I recall correctly you also need to make a selection of the full name, not only the login name. If your database doesn't have that, just select the same as for login.

**Comment by Alejandro888** [comment]
Thank you it worked, nice!

**Comment by Alejandro888** [comment]
Thank you, I have post other issue [https://github.com/nextcloud/user_sql/issues/40](url), can you advice on   that please? Thank you
