### ISSUE TITLE
[interaction] autocomplete should be filtered when you type

### ISSUE THREAD

**Issue by pedro-nonfree** [nextcloud/user_sql#43]
This is an issue of v4.0.0-rc2

It was working in v.3.1.0: while you type, the autocomplete/possibilities are being reduced. Now the autocomplete possibilities remain intact and It does not matter if you type more

**Comment by mlojewski-me** [comment]
Fixed (develop branch):
https://github.com/nextcloud/user_sql/commit/a257855e07ec81b580f401da65f17420d099fafd
https://github.com/nextcloud/user_sql/commit/ecb04a331b5196bde44a74212925326ff1a92075
