### ISSUE TITLE
wordpress not working

### ISSUE THREAD

**Issue by pedro-nonfree** [nextcloud/user_sql#44]
Hi,

trying v4.0.0-rc2 :)

I'm the author of this issue https://github.com/nextcloud/user_sql/issues/36

so I'm using MariaDB

I think it never worked, says "Wrong password."

Anyway, now I have deployed v4.0.0-rc2 and I used the recommended options for wordpress 

https://github.com/nextcloud/user_sql#wordpress

still "Wrong password."

![2018-06-18-222546_676x602_scrot](https://user-images.githubusercontent.com/39959198/41560170-936f2a20-7346-11e8-8134-bb6c5580f41a.png)

**Comment by pedro-nonfree** [comment]
[This link](https://stackoverflow.com/questions/1045988/what-type-of-hash-does-wordpress-use) suggests that they use [phpass](http://www.openwall.com/phpass/)

**Comment by mlojewski-me** [comment]
I solved the problem, you can now check develop branch. Just use "Portable PHP password".
