### ISSUE TITLE
Adding hash compatibility for Woltlab Suite 

### ISSUE THREAD

**Issue by thedespo** [nextcloud/user_sql#45]
Hello, it is possible to implement the hash algorithm from Woltlab?
Unfortunately it is currently not possible to authenticate the users from the Woltlab database with any hash option which is already implemented to this plugin.

Info:
The Woltlab dev´s says that he are using DoubleSalted bcrypt.
Here is a link which i became from the woltlab dev´s: https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/util/PasswordUtil.class.php

If you need any more information, please don't hesitate to write me.

It would be very great if you can implement this.

regards
Patrick

**Comment by mlojewski-me** [comment]
I see it supports several implementations. Some of them are already implemented.
Which one do you have in your mind? wcf2 is double salted.

```
		'ipb2',		// Invision Power Board 2.x
		'ipb3',		// Invision Power Board 3.x
		'mybb1',	// MyBB 1.x
		'phpbb3',	// phpBB 3.x
		'phpass',	// phpass Portable Hashes
		'smf1',		// Simple Machines Forum 1.x
		'smf2',		// Simple Machines Forum 2.x
		'vb3',		// vBulletin 3.x
		'vb4',		// vBulletin 4.x
		'vb5',		// vBulletin 5.x
		'wbb2',		// WoltLab Burning Board 2.x
		'wcf1',		// WoltLab Community Framework 1.x
		'wcf2',		// WoltLab Suite 3.x / WoltLab Community Framework 2.x
		'xf1',		// XenForo 1.0 / 1.1
		'xf12',		// XenForo 1.2+
		'joomla1',	// Joomla 1.x
		'joomla2',	// Joomla 2.x
		'joomla3',	// Joomla 3.x
		'phpfox3',	// phpFox 3.x
		'cryptMD5',
```

**Comment by thedespo** [comment]
Hi, i am using WoltLab Suite 3.x. So the hash for wcf2 (double salted).

**Comment by mlojewski-me** [comment]
Can You see how wcf2 hashes word "password"? It would be greate if you get this value from database exactly how it is stored. I need it for unit test.

**Comment by thedespo** [comment]
Sure, if i am at home today evening i will do this by using my Account.

**Comment by thedespo** [comment]
So, here is the hash for the word "password" which is stored in the WoltLab Database.

Hash: $2a$08$XEQDKNU/Vbootwxv5Gp7gujxFX/RUFsZLvQPYM435Dd3/p17fto02

**Comment by mlojewski-me** [comment]
Done. The change is in develop branch.

**Comment by thedespo** [comment]
Awesome! It´s working. Thank you a lot!

**Comment by SilentPain96** [comment]
I have the same problem he gets username and email but he keeps saying that the password doesn't match
