### ISSUE TITLE
Add support for algorithm parameters

### ISSUE THREAD

**Issue by mlojewski-me** [nextcloud/user_sql#46]
Developed on: https://github.com/nextcloud/user_sql/tree/feature/issue%2346

In settings admin panel add hash algorithm options eg.

- CryptBlowfish -> cost,
- CryptArgon2 -> memory cost, time cost, threads
- ...

Now workaround is to change it in code (constructor).

TODO:
 - [x] Add dynamically generetaed numer fields in admin panel when choosing appropriate hash (Hash interface should now return array with name, visible name, default value and range - new method)
 - [x] Add saving parameters in database
 - [x] Add verifying new parameters range when saving configuration
 - [x] Check and use these parameters when creating new hash instance
 - [x] Add description of parameters in readme
 - [x] Update changelog

**Comment by poVoq** [comment]
Maybe an option to specify the php hash() function's algorithm would also be nice?
See: http://php.net/manual/en/function.hash.php

I am currently trying to get a site working that uses the hash() 'whirlpool' algorithm and am unsure where to start modifying the code.

**Comment by KrystinaMir** [comment]
Hello! After activating the add-on in the logs indefinitely:

Debug | user_sql | The application properties has been loaded.
Warning | user_sql | There's no distributed cache available, fallback to null cache. | 

How to fix! Thanks in advance for the answer!
