### ISSUE TITLE
Feature Request: add quota managment from SQL

### ISSUE THREAD

**Issue by JanKraljic** [nextcloud/user_sql#52]
Quota App is really useful for limiting users Disk Space. 

It would be really nice it there would be in option integrate user_sql with Quota, so there would be possible so set Quota in SQL and Nextcloud would read that information. For example like additional tables like done for groups.

Thank you for doing really useful plugin.

**Comment by mlojewski-me** [comment]
I have to check where quota property is stored, but I think it would be something similar to email sync, so there should bo no problem implementing this.

**Comment by mlojewski-me** [comment]
Done, you can check develop branch.

**Comment by JanKraljic** [comment]
Wau, thank you. I would test asap
