### ISSUE TITLE
Can't get login to work with Wordpress

### ISSUE THREAD

**Issue by J-Evolve** [nextcloud/user_sql#53]
Hello there,
I just recently found your awesome app and after successfully connecting my wordpress database and table, I was able to view all the users in the list.
Unfortunately despite testing all the encryption methods I wasn't able to log in with my Wordpress user.
I am using the most recent version 3.1.0 for Nextcloud 13.
Any known issues you are aware about or things I should take a look at to make it work?
Kind regards!

**Comment by mlojewski-me** [comment]
The [new version](https://github.com/nextcloud/user_sql/milestone/1) is in develop stage I plan to release it in august along with Nextcoud 14.
For now you can use version from [develop branch](https://github.com/nextcloud/user_sql/tree/develop).

There had been an issue involving wordpress but it is fixed already in develop
https://github.com/nextcloud/user_sql/issues/44

**Comment by J-Evolve** [comment]
My bad. I didn't check the closed issues. Thanks so much for that quick and effective solution. Works like a charm. Looking forward to your new version !
