### ISSUE TITLE
It is working but log gets flooded with unsupported type messages

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#55]
I have a strange issue that my Nextcloud log is flooded with this message:

`Error | OC_USER_SQL | Failed to connect to the database: Unsupported type:`

Despite everything working fine. The type of the database in question is MySQL with InnoDB.

Maybe related to the fact that I created an SQL View to pull the group information?

**Comment by mlojewski-me** [comment]
The description of the issue you gave is very poor.
Can you write at least which version of nextcloud, user_sql, mysql you use?
I think it applies to old versions.

**Comment by poVoq** [comment]
Sorry.
Nextcloud 13.0.4
User_SQL 3.1.0 (latest from app store)
MySQL: 5.7.22

Running on a shared host at netcup.de

**Comment by mlojewski-me** [comment]
It has to be something with the _sql_driver_ property.
Do you have php_mysql driver installed?

**Comment by poVoq** [comment]
Would it be working otherwise?
This is on a shared hosting environment, but my phpinfo() tells me that there is pdo_mysql installed and mysqlnd 5.0.12-dev - 20150407

**Comment by poVoq** [comment]
Ah, if that helps, the "flooded" is exactly 2x the message every hour when my cron runs, so I guess it is somehow related to the automatic syncing?

**Comment by mlojewski-me** [comment]
I think it is not worth to spend time to fix this issue because new version which is comming out soon don't have this bug. Also two messages per hour is not that many.
