### ISSUE TITLE
Support custom salts?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#56]
I seem to be working with a database that has a custom salt in it's database for each account in addition to the password hash. This is apparently done with the php hash() function utilizing the 'whirlpool' algorithm.

So maybe it would be possible to add a field where a account salt column could be selected?

Thanks a lot!

**Comment by mlojewski-me** [comment]
Have you seen this commit?
https://github.com/nextcloud/user_sql/commit/a2b65f144c51be46335d34d12f3310e3533e4329

**Comment by poVoq** [comment]
Oh, awesome :) I'll close this then.
