### ISSUE TITLE
Install Problem: admin-form does not show up

### ISSUE THREAD

**Issue by JoergAW** [nextcloud/user_sql#57]
Can not enter sql-admin data in ...nextcloud/index.php/settings/admin/additional (as admin)
App shows up in app-list, can be activated and deactivated.  
Tested several ways to install (download, app store) in version 4.0.x and 3.1.0.

I need some advise.  Thanks!

**Comment by karlja** [comment]
in 4.0.0rc2 there is a separate menu item for the user_sql settings: index.php/settings/admin/user_sql
