### ISSUE TITLE
Home Mode "Query" does not support datadirectory/home location setting

### ISSUE THREAD

**Issue by karlja** [nextcloud/user_sql#59]
Nextcloud Version: 13.0.5
user_sql Version: master branch (4.0.0-rc2)

### Settings
```
Home mode: Query
UserTable.Home: id
datadirectory: /var/www/oc_data
Home Location: /var/www/oc_data
```

### Issue
I would have expected that with the setting for datadirectory and/or Home Location files are saved under: `/var/www/oc_data/[id]`
However, files are saved under: `/var/www/public_html/[id]`
_(where [id] is the user's id)_

**Comment by mlojewski-me** [comment]
You have to set _Home mode_ to _Static_
And _Home Location_ to _/var/www/oc_data/%u_
Of course the /var/www/oc_data/ should be writable by your server's user.

I improved description of these parameters:
https://github.com/nextcloud/user_sql/commit/8b1fb2306efd53370e5f99af1ad5395142c14e2a

**Comment by karlja** [comment]
Thank you for the suggestion, but I would need to define "home" as a separate column in the user table definition, which - from my understanding - is only possible if I use the query mode.

**Comment by mlojewski-me** [comment]
If you want to provide for each user home location you can use query mode and set home column which value is its home location

**Comment by karlja** [comment]
That is what I did, but as mentioned, the setting would append the location defined in the home column to the public html folder instead of the setting defined in NC settings (datadirectory) or the user_sql settings (Home Location).
