### ISSUE TITLE
Feature Request: Differentiate between userid and username

### ISSUE THREAD

**Issue by karlja** [nextcloud/user_sql#60]
I would suggest to allow to differentiate between `userid` and `username` in the settings (and include username as a new attribute), because:

- the username is often required for login purposes as well as sharing (rather than the userid)
- the username might be subject to change, which would cause issues with the files and shares in NextCloud
- the username could include special characters (based on the system you are connecting to) that might not be treated well by NextCloud for e.g. login or internal referencing

What are your thoughts?

**Comment by mlojewski-me** [comment]
Look at this interface https://github.com/nextcloud/server/blob/master/lib/public/UserInterface.php
There's only one field which refers to user `uid` = `username.`
Username should be unique and should not be changed,
so I don't think your request is possible to implement.

**Comment by karlja** [comment]
Hi Marcin,

Thank you for the response and thoughts.

Assuming that I have a user table (or view) as follow: `uid | username| displayname | email`. I would like to use the `uid` for internal handling within NextCloud, the `username` solely for login purposes, and define the `DisplayName` as `Name (username)` (or plain `username` or something if someone prefers that).

Hence, my thought was that:

- on login, the user would provide his `username` (or `email`)
- the `UserBackend::checkPassword` would use the `username` as "`uid`" for validating the password
- if the password is correct, the `UserBackend::checkPassword` would return the real `uid` (similar as it is done when you use the email for login

That way I would not need the `username` and `uid` as defined field in the user interface.


UserBackend::CheckPassword: https://github.com/nextcloud/user_sql/blob/b1b1ffb04fd462f8a5f98a8cdd69edefb7788831/lib/Backend/UserBackend.php#L261

**Comment by karlja** [comment]
Thank you for implementing this as standard feature in the meantime :-) @mlojewski-me
