### ISSUE TITLE
Which version should I use? (Nextcloud 13.0.5, SHA512 hashes)

### ISSUE THREAD

**Issue by pacohope** [nextcloud/user_sql#63]
Hi. I'm trying to enable this module. The only way I seem to be able to install is manually. (I originally began life on ownCloud 7 and have been upgrading ever since, it's entirely possible my app store doesn't work quite right...). I've been installing apps by untarring or git cloning into the right `apps` directory on my server.

If I go the [app store page](https://apps.nextcloud.com/apps/user_sql), it would have me install version 3.1.0, which (as far as I can tell) doesn't support SHA512 hashes. I can find it in the apps list and enable it. I can configure the database parameters correctly, and it connects to the database. But (I think) the reason login fails is because my password hashes are unsupported. (Password hashes in my database look like this: `{SSHA512}abcde+ABCDE...`)

If I follow the instructions in the [README](https://github.com/nextcloud/user_sql/blob/master/README.md) and do a `git clone`, I will see the app in the list of apps. I can't enable it. I get a warning that

> App "User and Group SQL Backends" cannot be installed because it is not compatible with this version of the server.

Am I stuck? Is there any workaround or do I need to wait for Nextcloud 14?

**Comment by mlojewski-me** [comment]
I think you can use [this commit](https://github.com/nextcloud/user_sql/commit/4d48a58bf9a8f1e34e06a788660986ad5cf76dea) and use SSHA512
