### ISSUE TITLE
Add support for salt in SHA512 Whirlpool?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#65]
I have an external php website (HubZilla) that creates salted whirlpool hashes like this:
```
$salt = random_string(32);
$password_encoded = hash('whirlpool', $salt . $password);
```
Which I assume is the Whirlpool of this app? However it is clearly salted, which seems to be not supported? I tried and so far it fails sadly.

Would be much appreciated if the option to salt the Whirlpool hash would be added. Thanks!

**Comment by poVoq** [comment]
Looking at this code: https://github.com/nextcloud/user_sql/blob/master/lib/Crypto/SHA512Whirlpool.php
it seems like this is actually being double hashed?

So in that case I would just need regular whirlpool with salt ;)

**Comment by mlojewski-me** [comment]
Adding regular whirlpool hash is very simple.
I will add it momentarily.

About getting salt from dedicated database column it is done in `UserBackend` in functions:
- checkPassword
- setPassword

```
        if ($user->salt !== null) {
            $password .= $user->salt;
        }
```
But setting password does not generate new salt so its kind of week.
The column `salt` is also explained in README file.

**Comment by mlojewski-me** [comment]
I think that there should be also a flag which mean whether a salt from external column should be appended or prepended to password. Right now salt is only appended.

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/7d35d0a67fd93d2e73351d12cf86d30a288f939e

**Comment by mlojewski-me** [comment]
Do you still new to prepend salt from external column?

**Comment by mlojewski-me** [comment]
I added the toggle https://github.com/nextcloud/user_sql/commit/2ef7716527f1a82455ff9d5b21cc0aa22f14ad19 but I have not tested it, can you do it for me and close the issue if it is correct?

**Comment by poVoq** [comment]
Sure, will do tomorrow. Thanks a lot!

**Comment by poVoq** [comment]
Works with HubZilla. Thanks a lot!
