### ISSUE TITLE
Update Only 1 column

### ISSUE THREAD

**Issue by sheychen290** [nextcloud/user_sql#67]
DB: Mariadb
I'm using a view as user table to "merge":
- nextcloud data (quota, password, ...)
- standard user data (uid, display name, mail, ...)

Users and groups load works great.
But password cache (and maybe quota or display) fails because nextcloud try to update all columns and views with join doesn't support it.

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE nextcloud_users_view SET password = :password, display_name = :name, mail = :email, quota = :quota WHERE uid = :uid' with params ["xxx", "xxx, "xxx", "xxx", "xxx"]: SQLSTATE[HY000]: General error: 1393 Can not modify more than one base table through a join view 'auth.nextcloud_users_view'
```

It's possible/plained to limit updates to "really updated field" like ```UPDATE nextcloud_users_view SET password = :password WHERE uid = :uid``` ?

ps: sorry for my poor english.

**Comment by mlojewski-me** [comment]
The update is invoke in 4 cases, when the following columns change:
- password
- display name
- email sync
- quota sync

There is one update query implemented where all of this fields get updated (if defined) even if only one field is changed.

I think it's a good idea to implement this as Mariadb support view updates.

**Comment by mlojewski-me** [comment]
Done https://github.com/nextcloud/user_sql/commit/e14ca585711a7f9e54b5fd849a447ca8a7f47dea
