### ISSUE TITLE
Group functionality not working in 4.0

### ISSUE THREAD

**Issue by Bubu** [nextcloud/user_sql#68]
After upgrading to NC 14 and user_sql v4.0 the groups aren't fetched from the DB anymore.

I refilled my db setup like before but can't get groups to work.
Any idea what might be the reason for this?

Also I'm not quite sure of the role of the Group table. As far as I can see I didn't use that for the previous version and did get group functionality.

Did I get this correct that it just has to contain a list of available group names whcih are in turn referenced in the user_group table?

**Comment by mlojewski-me** [comment]
There are 5 mandatory fields for group backend to work:

Group table:
- Table name
- Group name

User group table:
- Table name
- Username
- Group name

Everything is describe in README with example DDL for tables.
Group table should list all groups with their properties.

If you don't have dedicated table for that you can create view from 'user_group' table eg. 
CREATE VIEW groups AS SELECT DISTINCT group_name FROM user_group;
And then fill configuration with:
Group table:
Table name -> groups
Group name -> group_name

**Comment by Bubu** [comment]
Thank you for your reply.
I have created the view and configured it accordingly. This is how the config look like now:
![image](https://user-images.githubusercontent.com/105185/46899951-dd6d1880-ce9a-11e8-8ea2-b6a908021fc2.png)

I still don't get the user-group mapping applied from the db. There are no errors in the log. Any ideas, how I can debug this?

**Comment by mlojewski-me** [comment]
Set value of Group table -> Display name to `group_names`.
 
I made a fix to get this value from Group name column if not set
https://github.com/nextcloud/user_sql/commit/9ab6df0f7699b8b5148bee10fa982b20f64eb9c3

**Comment by Bubu** [comment]
> Set value of Group table -> Display name to group_names.

:+1: that fixed it. I thought I did try that already beforehand yesterday without luck. Not sure what happened then.

Thanks for the help and for the fix!
