### ISSUE TITLE
Can't authenticate after updating to 4.0

### ISSUE THREAD

**Issue by Bubu** [nextcloud/user_sql#69]
I get the following error in the log:

> hash_equals(): Expected user_string to be a string, null given at /var/www/nextcloud/apps/user_sql/lib/Crypto/Phpass.php#55

Table configuration like here: https://github.com/nextcloud/user_sql/issues/68#issuecomment-429501781

Hash algorithm is phpass for a joomla installation.

**Comment by mlojewski-me** [comment]
I looks like you have NULL value stored in your database for user password. Can you confirm that?
If do I will make a fix not to write error in that case.

**Comment by Bubu** [comment]
There are no NULL values in the password column, what I noticed though is that apparently 4 users still follow the old joomla password scheme. These are however not the users I got the login error with.

**Comment by Bubu** [comment]
My hashes look something like this: `$2y$10$[...]`

**Comment by Bubu** [comment]
Weird. Everyone on the internet is saying that joomla uses phpass... :thinking: 

Anyway, this is working now, sorry for the noise and thanks for your time.
