### ISSUE TITLE
Wordpress Login Discrepancy

### ISSUE THREAD

**Issue by J-Evolve** [nextcloud/user_sql#71]
Hello,
i am using user_sql (User and Group SQL Backends	4.0.1) in its latest version with nextcloud 14.0.3 and the latest wordpress version. User sync / login is working properly with your instructions (using portable PHP password).
There are only two slight issues that occur on my end:
1. Wordpress username is not case sensitive (whereas i think nextcloud has case sensitive users). this results in the users being able to log in with any cased form of their username. but only if they use the exact case they signed up in wordpress with the folder permissions and the access in nextcloud will be correct.

2. Using the wp stored email address to sign up doesn't work for my users currently

Are those issues known bugs? Or is there possibly a mistake in my configuration?

Kind regards and thanks in advance!

**Comment by mlojewski-me** [comment]
Those are not bugs but features.
I think it is easy to implement both of them by adding checkboxes accordingly: case insensitive username, allow to login with email, but with the second one emails have to be unique.

**Comment by J-Evolve** [comment]
ah thanks for the quick response. great to hear that it is propably going to be a feature. emails usually are unique and anyway the preferred login method of most (of my) users. thanks again. 
you plugin is so very helpful and i am glad i found it!
