### ISSUE TITLE
no case sensitiviy at login

### ISSUE THREAD

**Issue by dpauso** [nextcloud/user_sql#73]
By this app users are allowed to login with "user" and "User" (tested with newest joomla and "blowfish"-cryption)

in my eyes thats an issue, because sharing at nextcloud only knows "User" or "user". For nc-sharing this are two different users. "User" can't see any shared folders, but "user" can. Thats confusing for users.

Nextcloud 14.0.3 / User_Sql 4.0.1 / Joomla 3.8.13

**Comment by mlojewski-me** [comment]
I think this is MySQL problem as describe here https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html

To solve this issue you can check this conversation:
https://stackoverflow.com/questions/3969059/sql-case-sensitive-string-compare

The query in application looks like this where :uid parameter is not change:
```
SELECT username AS uid, display_name AS name, email AS email, null AS quota, null AS home, true AS active, false AS avatar, null AS salt, password AS password FROM sql_users WHERE username = :uid
```

**Comment by dpauso** [comment]
Thank you!

ok, i understand the problem, but does this only happen because i use the user_sql app? 
For me, it would be great, if nextcloud or the app disallow login with the wrong case-sensitive username

**Comment by mlojewski-me** [comment]
Added 'force check username in PHP code when case sensitive' task in https://github.com/nextcloud/user_sql/issues/74
