### ISSUE TITLE
Add support for remine password hashes

### ISSUE THREAD

**Issue by jamasi** [nextcloud/user_sql#77]
Redmine is using password hashes that are generated as this:

    Hash = SHA1( salt + SHA1( password ) )

I'm not sure if user_sql can be configured to work with those, but if it can it would really help if the documentation would walk you through setting up this scenario.
It would be perfect if one could simply select "redmine" from the dropdown and all fields would be filled with the correct default values.

**Comment by mlojewski-me** [comment]
There's no such algorithm right now I will add it soon.

**Comment by mlojewski-me** [comment]
commit 8e80480eaa62d0998236813608523e1ca235ec9c

**Comment by nd-** [comment]
Hi @jamasi, do you have an example of a configuration that works with NC + user_sql and Redmine that you could share ?

Nextcloud 22.2.3 and Redmine 4.2.3.stable here.

Connection to the PostgreSQL DB from Redmine is ok, I setup `users` and `group_users` fields, but I don't know how to retrieve users email (there in a distinct `email_adresses` table).
And if I use `login` as UID in `users` table config, I have an query error in /settings/users in NC.
I'm a bit lost... :-/
