### ISSUE TITLE
Hide "password change form"

### ISSUE THREAD

**Issue by tomtomas99911** [nextcloud/user_sql#78]
Hi,
in this app you can disable password change for users, but they still see "password change form" in settings - so users are confused and they think that they can change their password.

Is possible to add new feature to hide "password change form" in settings for users?

Thank you!

**Comment by mlojewski-me** [comment]
Hi, I think it's nextcloud core feature not app feature.

**Comment by tomtomas99911** [comment]
unfortunately it is not core feature :(. So it is not good idea implement this feauture to this app?

**Comment by mlojewski-me** [comment]
I don't think it is possibile, because you cannot control core funcions from app

**Comment by mlojewski-me** [comment]
Ok, I will check it soon

**Comment by mlojewski-me** [comment]
commit: c6c345873cf5d7cfe5d71146995e9da6b0a6a597
