### ISSUE TITLE
Password error on sha512 with salt

### ISSUE THREAD

**Issue by cristianopolicarpo** [nextcloud/user_sql#79]
Hi.

I'm having a password error while login on sha512 with salt.

I've tried setting up with pretty much all the algorithms available in the app.

Any idea how I can solve this?

Thank you!

**Comment by cristianopolicarpo** [comment]
> Can you provide error message/log?

Maybe I did not express myself well. Actually not a error, I simply get the message that my password is incorrect.

In my database the word "password" in sha512 is:

B109F3BBBC244EB82441917ED06D618B9008DD09B3BEFD1B5E07394C706A8BB980B1D7785E5976EC049B46DF5F1326AF5A2EA6D103FD07C95385FFAB0CACBC86

And in the readme.md file of the app, this result does not exist.

I think I'm using an incompatible algorithm.

Any help would be much appreciated.

Thank you!

**Comment by mlojewski-me** [comment]
Now I get it, you use simple sha512 hash, neither of SSHA512 or SHA512 (Crypt).
I will add it soon

**Comment by cristianopolicarpo** [comment]
> Now I get it, you use simple sha512 hash, neither of SSHA512 or SHA512 (Crypt).
> I will add it soon

Cool, it would be great to add simple sha512 support.

Thanks again!

**Comment by mlojewski-me** [comment]
commit: fb029b8b27404ea78a9581f5bb7e2f664ea603ba
