### ISSUE TITLE
User Dsiaply Issue

### ISSUE THREAD

**Issue by glennrossi** [nextcloud/user_sql#80]
Using NextCloud 14.0.4 and your plugin.  User display from Admin account only displays first 25 users from external database.  Not using groups.

**Comment by glennrossi** [comment]
TypeError: Return value of OCA\UserSQL\Backend\UserBackend::getDisplayName() must be of the type string, null returned at /var/www/html/nextcloud/apps/user_sql/lib/Backend/UserBackend.php#272

**Comment by mlojewski-me** [comment]
Is display name column nullable? If so this could be reason of error.

**Comment by mlojewski-me** [comment]
4be9acb32c983bccfe77b2eea71053effe17a9ad
