### ISSUE TITLE
nextcloud 15

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/user_sql#81]
Hi, any plan to support nextcloud 15 release?
Thanks.

**Comment by KrystinaMir** [comment]
Also interested! Thanks for reply!

**Comment by KrystinaMir** [comment]
If anyone is interested! My good friend helped me! Go to: /var/www/nextcloud/apps/user_sql/appinfo / info.xml and change <next cloudmin-version= " 14 "maxversion= "14"/> to <next cloud min-version=" 15"max-version=" 15 " /> everything works!

**Comment by mlojewski-me** [comment]
I plan to release a new version at the end of this week
https://github.com/nextcloud/user_sql/milestone/3

**Comment by mlojewski-me** [comment]
commit: e2c8759cbe97554b4d838eb60ed18026c4e8863d
