### ISSUE TITLE
user migration

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/user_sql#82]
Hi, I want migrate nextcloud user to user_sql, both db have user infomation,
when I type occ user:info  user1
I still can see user1 is backend: Database

I want change it to backend: User SQL
(let the user change password in user_sql database).

What is the proper way to do that? 

Thanks.

**Comment by mlojewski-me** [comment]
I think when you change password it is changed in all backends.
If you want users to be only in User SQL Backend you should probably delete them from other backends, which is of of the scope of this plugin.

**Comment by johnwmail** [comment]
No, it is not, it change nothing for SQL Backend (at least on my system)
Is it safe to delete user with occ?
Thanks.

**Comment by mlojewski-me** [comment]
I don't know if it's save you have to test it? Do you set allow password change checkbox?

**Comment by johnwmail** [comment]
> I don't know if it's save you have to test it? Do you set allow password change checkbox?

Yes, it work, delete user with occ, thanks.

**Comment by schniepp** [comment]
I would also like to switch over existing users to SQL backend (preserving the username). However, I would like to also preserve all files, permissions, comments, etc., so basically everything that user did. The user should not experience any difference from the backend being switched to a different backend. (Other then, perhaps, having to reset the password.) I am worried that deleting the user will delete all of this. Is there a way to do this?
And then, I would like to do the same thing with groups. Currently, I have my groups only sitting in nextcloud. However, I have given a lot of permissions to individual files, folders etc. based on group name. Now, I would like to switch the groups over to the SQL database. In other words, I will have groups with the same name in the SQL database, and have it that users that are members of the SQL groups get all the permissions that they had when they were a member of a group of the same name that was an internal NC group. Is this possible? (I am hoping my explanation is comprehensible.)
