### ISSUE TITLE
Error when same column names

### ISSUE THREAD

**Issue by fsdfasf** [nextcloud/user_sql#83]
I had a column title selected in grouptable and user group table which gave te following error

{"reqId":"XBvFe1RK83bgdbvvpRjMRwAAAA8","level":3,"time":"2018-12-20T17:38:19+01:00","app":"index","method":"GET","url":"\/cloud\/settings\/users","message":{"Exception":"Doctrine\\DBAL\\Exception\\NonUniqueFieldNameException","Message":"An exception occurred while executing 'SELECT **title** AS gid, **title** AS name, false AS admin FROM jos_usergroups, Joomla_NC_groupmapping WHERE **title** = **title** AND username = :uid ORDER BY title' with params [\"admin\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1052 Column 'title' in field list is ambiguous","Code":0,"Trace":[{"file":"\/home\/deb107700\/domains\/eur-``\\\

Maybe you can use a table-name.column-name construction to make it more robust?

**Comment by mlojewski-me** [comment]
I haven't noticed that I will fix it later today.

**Comment by mlojewski-me** [comment]
fixed in v4.2.1
