### ISSUE TITLE
Problem with "Provide avatar" field with user_sql 4.2.1

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/user_sql#86]
As I allow all my users to change their avatars I used a trick in the previous versions, I added 'true' as fieldname in the "provide avatar" field. I wanted to avoid to add a field that in all cases has "True" as value. This worked fine until the new release. It changes the fieldname to u.true and thus the SQL statement fails 

`("SELECT u.username AS uid, u.name AS name, u.x_email AS email, null AS quota, null AS home, u.active AS active, u.true AS avatar, null AS salt, u.password AS password FROM mailbox u ").`

As I believe it is more common to have a general "allow avatar" rule than a "per user" rule it would be nice to have this option back.

**Comment by mlojewski-me** [comment]
I will add checkbox which will indicate default value for "Provide avatar" if column is not set

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/8370f4b8d00d889e6a918c694ab4c315c1f437a0
This week I will make a new release.
