### ISSUE TITLE
Username autocompletion in share dialog is not working for users provided via user_sql

### ISSUE THREAD

**Issue by paspil** [nextcloud/user_sql#88]
Tested with Nextcloud 14/15 and [mlojewski-me/user_sql-vagrant](https://github.com/mlojewski-me/user_sql-vagrant).
"Allow username autocompletion in share dialog." is checked. Authentication works and the users show all up in the settings/users view.

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/a06e3163274188f0d56fdeea1fa7f350f1eb4ee0

**Comment by mlojewski-me** [comment]
Now only uids are searched, so I will extend it to display names.
I guess the same apply for groups.

**Comment by paspil** [comment]
Haven't testet groups yet. Try to connect to TYPO3 frontend users table and it looks like the TYPO3 groups are not mappable to the options in user_sql. Nextcloud own groups don't have a display name as far as I can see it.

**Comment by mlojewski-me** [comment]
solved with issue#91
