### ISSUE TITLE
Contact not showing in Nextcloud Talk

### ISSUE THREAD

**Issue by MatSarr** [nextcloud/user_sql#89]
Hello,
I use the user_sql to connect my wordpress user database to the nextcloud database. It's working great except for Nextcoud talk : only user created on nextcloud are showing in the contact page. Moreover, I can connect with any user, but with a user from wordpress database, the account always disconnect and the notifications aren't working.

I tried on a nextcloud 14.6 instance and a nextcloud 15 instance. Same issue.

**Comment by mlojewski-me** [comment]
Fixed along with #88
