### ISSUE TITLE
Password hash prefixes

### ISSUE THREAD

**Issue by cweiske** [nextcloud/user_sql#90]
I'm using Dovecot (IMAP/POP3) and Postfix (SMTP) on my server, with Postfix using [Dovecot's SASL authenticator](https://wiki2.dovecot.org/Sasl) as authentication backend.
Dovecot stores/expects password hashes [prefixed](https://wiki2.dovecot.org/Tools/Doveadm/Pw):

> All generated password hashes have a `{scheme}` prefix, for example `{SHA512-CRYPT}`

So passwords in my mail user database also look that way, e.g. `test`:

```
{SHA512-CRYPT}$6$vimyrTLCXXCk5VkM$DEZounk3pBpvnOTRnhNnniiKBaVP4xlP5SVGam4RNAW2tQ8H2eFd98zf5eV4CS6feYP6k4GTydeILyK5regt60
```

The user_sql plugin currently does not support such prefixes.

When I set user_sql password scheme to `SHA512 (crypt)` and adjust the code to strip off the leading scheme prefix, login works fine.

I have now several questions:

1. How should a patch look like that adds support for Dovecot password databases? A new settings checkbox "Strip {scheme} prefix" that modifies the password hash in `AbstractCrypt::checkPassword()`? Or should it automatically check if the hash contains a prefix and strip that?
2. This only works if all users are using the same hashing algorithm. With the prefixes, dovecot automatically chooses the right hashing algorithm itself and thus is able to work with different ones, which is necessary when upgrading to a more secure algorithm every couple of years. To support that, a new Crypto class would need to be implemented, which could simply act as proxy to the other ones.

What do you think?

**Comment by mlojewski-me** [comment]
What about making a database view which strips {scheme} prefix and using Unix (Crypt)?
