### ISSUE TITLE
Email sync not fully working

### ISSUE THREAD

**Issue by cweiske** [nextcloud/user_sql#92]
When activating email sync, user_sql uses `\OCP\IConfig::setUserValue()` to update the email address.
Unfortunately, the user does not see the email address in nextcloud when editing the profile.

It seems that Nextcloud 15 writes the profile email address to 3 locations:

- oc_accounts
- oc_cards_properties
- oc_preferences

`IConfig::setUserValue()` only updates oc_preferences, but not the other two locations.

**Comment by mlojewski-me** [comment]
Resolved with merge
