### ISSUE TITLE
XenForo bcrypt

### ISSUE THREAD

**Issue by Tealk** [nextcloud/user_sql#94]
Hello,
 
I wanted to connect my Nextcoud with the database of XenForo.

The last information I could find is that it is stored in bcrypt in the table xf_user_authenticate.
https://xenforo.com/community/threads/external-password-username.146601/

**Comment by mlojewski-me** [comment]
According to https://xenforo.com/community/threads/password-hash.138775/
app should work with algorithm set to Blowfish (Crypt) and PHP 5.5 or above

**Comment by Tealk** [comment]
This is the old Xenforo version, currently ARGON2ID is used:
https://xenforo.com/community/threads/welcome-to-xenforo-2-1-assorted-improvements.155901/#post-1294633

**Comment by mlojewski-me** [comment]
PASSWORD_ARGON2I is supported I will add PASSWORD_ARGON2ID

**Comment by mlojewski-me** [comment]
fixed in https://github.com/nextcloud/user_sql/commit/9644bce09c2d21bbe8cbf475c4987a97d9ae82e9
will be released soon
