### ISSUE TITLE
Column "Active" and user status "disabled"

### ISSUE THREAD

**Issue by mko24** [nextcloud/user_sql#95]
Hi, first and foremost: Thanks for the great app!

After updating to NextCloud 14.0.6 and user_sql 4.3.0 all previous inactive users (Column Active = 0) will show up in the user administration on the tab "Everyone". Also users can select such an "inactive" user for sharing files. In the previous release (Nextcloud 13 and user_sql 3.1.0) the user will not be shown and are also not selectable for sharing.
By the way: Disabling a user in Nextcloud will not change the column "Active".

**Comment by mlojewski-me** [comment]
The description in readme tells:
**Active** | Flag indicating if user can log in. | Optional.<br/>Default: true.

So I thing that a new checkbox should be added which extends this flag behavior. I will do it soon.

**Comment by mko24** [comment]
Maybe there's a way to sync the "Active" flag with the user status "Disabled" of Nextcloud?

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/1283fd68fc2063dc934c3ac365c2c3dc048fc719
