### ISSUE TITLE
Nextcloud Client asks for password very often

### ISSUE THREAD

**Issue by Thommy1231** [nextcloud/user_sql#96]
Hello,
we use for our nextcloud the user sql app
Serveral users have got the problem that the client (with different OS) asks for the password sometimes multiple times in a period of 2 hours

the problem occured only by user they authentficate with user sql
The normal Nextcloud users haven't got this issue

Have anyone an idea? Is the problem maybe in our server configuration?

Notice: we have 8000 users

**Comment by mlojewski-me** [comment]
I have no idea. Is is single server instance? Maybe php settings are not sufficient for that amount of users, and gc cleans their sessions?
