### ISSUE TITLE
database password in config.php

### ISSUE THREAD

**Issue by Thom1b** [nextcloud/user_sql#99]
Hi,

It's more a pull request than an issue but I don't understand "new pull request" on github.
Anyway I think it could be better for security reason to have the hostname, database name, user name and **password** of the database in config.php instead of the nextcloud db. This way the password is not stored in the database in plain text.

Am I wrong? What do you think?

Have a nice day!

**Comment by mlojewski-me** [comment]
I think I can add them as system properties, in that way they will be stored in config.php but I think it should be choosable where to store them with default option as it is now.

**Comment by mlojewski-me** [comment]
https://github.com/nextcloud/user_sql/commit/94714ae987324f33c39c71013bb58ae26cb91588
